version: '3'
services:
    streamlit-app:
        container_name: ${COMPOSE_PROJECT_NAME} # 起動時のコンテナ名
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
            - ROOT=TRUE # コンテナ内にroot権限を持たせる
            - NEO4J_URI=${NEO4J_URI}
            - NEO4J_USERNAME=${NEO4J_USERNAME}
            - NEO4J_PASSWORD=${NEO4J_PASSWORD}
            - AURA_INSTANCEID=${AURA_INSTANCEID}
            - AURA_INSTANCENAME=${AURA_INSTANCENAME}
            - PROJECT_ID=${PROJECT_ID}
            - REGION=${REGION}
            - STAGING_BUCKET=${STAGING_BUCKET}
            - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
        volumes: 
            # - ".:/app" # [ホストのpath]：[コンテナのpath]
            - "${GOOGLE_APPLICATION_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}"
        ports: # ホスト：コンテナのポート番号を指定。ホストは他コンテナと番号被らないようにする
            - "8080:8080" 
        tty: true # コンテナを起動し続ける